# Generated by Django 5.1.2 on 2024-11-04 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloquearPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada_bloqueada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada_atual', models.IntegerField(default=1)),
                ('time_casa', models.CharField(max_length=50)),
                ('placar_casa', models.CharField(max_length=50)),
                ('time_visitante', models.CharField(max_length=50)),
                ('placar_visitante', models.CharField(max_length=50)),
                ('imagem_casa', models.ImageField(upload_to='emblemas_times')),
                ('imagem_fora', models.ImageField(upload_to='emblemas_times')),
                ('preenchido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RodadaOriginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada_atual', models.IntegerField(default=1)),
                ('time_casa', models.CharField(max_length=50)),
                ('placar_casa', models.IntegerField(default=0)),
                ('time_visitante', models.CharField(max_length=50)),
                ('placar_visitante', models.IntegerField(default=0)),
                ('vencedor', models.CharField(max_length=50)),
                ('finalizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Palpite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada_atual', models.IntegerField(default=1)),
                ('time_casa', models.CharField(max_length=50)),
                ('placar_casa', models.IntegerField(default=0)),
                ('time_visitante', models.CharField(max_length=50)),
                ('placar_visitante', models.IntegerField(default=0)),
                ('imagem_casa', models.ImageField(upload_to='emblemas_times')),
                ('imagem_fora', models.ImageField(upload_to='emblemas_times')),
                ('vencedor', models.CharField(max_length=50)),
                ('finalizado', models.BooleanField(default=False)),
                ('tipo_class', models.CharField(default='none', max_length=50)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('whatsapp', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('pagamento', models.BooleanField(default=False)),
                ('imagem', models.ImageField(default='imagens/perfil-null.png', upload_to='imagens')),
                ('avatar', models.ImageField(default='imagens/perfil-null.png', upload_to='thumb_img')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=0)),
                ('placar_exato', models.IntegerField(default=0)),
                ('vitorias', models.IntegerField(default=0)),
                ('empates', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bolao.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Verificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificado', models.BooleanField(default=False)),
                ('partida_atual', models.IntegerField(default=32)),
                ('partida_final', models.IntegerField(default=39)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
