# Generated by Django 5.1.2 on 2024-11-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_aposta',
            field=models.CharField(choices=[('normal', 'Normal'), ('por rodada', 'Por Rodada')], default=2, max_length=30),
            preserve_default=False,
        ),
    ]
