# Generated by Django 5.1.2 on 2024-11-09 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0004_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='usuario',
        ),
    ]
