# Generated by Django 5.1.2 on 2024-11-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0006_pontuacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontuacao',
            name='posicao_anterior',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pontuacao',
            name='posicao_atual',
            field=models.IntegerField(default=0),
        ),
    ]
