# Generated by Django 5.1.2 on 2024-11-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0007_pontuacao_posicao_anterior_pontuacao_posicao_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='posicao_anterior',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classificacao',
            name='posicao_atual',
            field=models.IntegerField(default=0),
        ),
    ]
