# Generated by Django 5.1.2 on 2024-11-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0008_classificacao_posicao_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='posicao_variacao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classificacao',
            name='posicao_anterior',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classificacao',
            name='posicao_atual',
            field=models.IntegerField(),
        ),
    ]
