# Generated by Django 5.1.2 on 2024-11-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0010_remove_classificacao_posicao_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='palpite',
            name='placar_exato',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='palpite',
            name='vitorias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='verificacao',
            name='verificado',
            field=models.BooleanField(default=True),
        ),
    ]
