# Generated by Django 5.1.2 on 2024-11-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0011_palpite_placar_exato_palpite_vitorias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquearpartida',
            name='bloquear_grafico',
            field=models.BooleanField(default=False),
        ),
    ]
