# Generated by Django 5.1.2 on 2024-11-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0013_bloquearpartida_bloquear_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='posicao_anterior',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classificacao',
            name='posicao_atual',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classificacao',
            name='posicao_variacao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
