# Generated by Django 5.1.2 on 2024-11-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0014_classificacao_posicao_anterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacao',
            name='posicao_atual',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
