# Generated by Django 5.1.2 on 2024-11-17 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0015_alter_classificacao_posicao_atual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_aposta',
        ),
    ]
