# Generated by Django 5.1.2 on 2024-11-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0016_remove_usuario_tipo_aposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(default='imagens/perfil-null.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(default='imagens/perfil-null.png', upload_to=''),
        ),
    ]
