# Generated by Django 5.1.2 on 2024-11-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0018_alter_usuario_avatar_alter_usuario_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodada',
            name='placar_casa',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rodada',
            name='placar_visitante',
            field=models.CharField(blank=True, null=True),
        ),
    ]
