# Generated by Django 5.1.2 on 2024-12-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0020_pagamento_data_pagamento_pagamento_participante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacao',
            name='partida_atual',
            field=models.IntegerField(default=1),
        ),
    ]
